/* tslint:disable */
/* eslint-disable */
/**
 * Swagger Data Provider
 * Документация API Провайдера Данных
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { GetPagedKnowledgeBases } from '../models';
import { KnowledgeBase } from '../models';
/**
 * ResearcherKnowledgeBaseApi - axios parameter creator
 * @export
 */
export const ResearcherKnowledgeBaseApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Send request for Knowledge Bases access
         * @param {string} id Knowledge Base identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        acceptRules: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling acceptRules.');
            }
            const localVarPath = `/api/v1/knoledge-bases/access`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2_Local required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken("OAuth2_Local", ["knowledge-base:read"])
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }

            if (id !== undefined) {
                localVarQueryParameter['id'] = id;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get Paged Knowledge Bases
         * @param {number} page Page number
         * @param {number} limit Page size
         * @param {Array<string>} [sort] Sorting type
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllKnowledgeBases: async (page: number, limit: number, sort?: Array<string>, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'page' is not null or undefined
            if (page === null || page === undefined) {
                throw new RequiredError('page','Required parameter page was null or undefined when calling getAllKnowledgeBases.');
            }
            // verify required parameter 'limit' is not null or undefined
            if (limit === null || limit === undefined) {
                throw new RequiredError('limit','Required parameter limit was null or undefined when calling getAllKnowledgeBases.');
            }
            const localVarPath = `/api/v1/knoledge-bases`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2_Local required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken("OAuth2_Local", ["knowledge-base:read"])
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (sort) {
                localVarQueryParameter['sort'] = sort;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get Knowledge Bases
         * @param {string} id Knowledge Base identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getKnowledgeBase: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling getKnowledgeBase.');
            }
            const localVarPath = `/api/v1/knoledge-bases/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2_Local required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken("OAuth2_Local", ["knowledge-base:read"])
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ResearcherKnowledgeBaseApi - functional programming interface
 * @export
 */
export const ResearcherKnowledgeBaseApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Send request for Knowledge Bases access
         * @param {string} id Knowledge Base identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async acceptRules(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await ResearcherKnowledgeBaseApiAxiosParamCreator(configuration).acceptRules(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Get Paged Knowledge Bases
         * @param {number} page Page number
         * @param {number} limit Page size
         * @param {Array<string>} [sort] Sorting type
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllKnowledgeBases(page: number, limit: number, sort?: Array<string>, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<GetPagedKnowledgeBases>>> {
            const localVarAxiosArgs = await ResearcherKnowledgeBaseApiAxiosParamCreator(configuration).getAllKnowledgeBases(page, limit, sort, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Get Knowledge Bases
         * @param {string} id Knowledge Base identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getKnowledgeBase(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<KnowledgeBase>>> {
            const localVarAxiosArgs = await ResearcherKnowledgeBaseApiAxiosParamCreator(configuration).getKnowledgeBase(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * ResearcherKnowledgeBaseApi - factory interface
 * @export
 */
export const ResearcherKnowledgeBaseApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Send request for Knowledge Bases access
         * @param {string} id Knowledge Base identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async acceptRules(id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return ResearcherKnowledgeBaseApiFp(configuration).acceptRules(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get Paged Knowledge Bases
         * @param {number} page Page number
         * @param {number} limit Page size
         * @param {Array<string>} [sort] Sorting type
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllKnowledgeBases(page: number, limit: number, sort?: Array<string>, options?: AxiosRequestConfig): Promise<AxiosResponse<GetPagedKnowledgeBases>> {
            return ResearcherKnowledgeBaseApiFp(configuration).getAllKnowledgeBases(page, limit, sort, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get Knowledge Bases
         * @param {string} id Knowledge Base identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getKnowledgeBase(id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<KnowledgeBase>> {
            return ResearcherKnowledgeBaseApiFp(configuration).getKnowledgeBase(id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ResearcherKnowledgeBaseApi - object-oriented interface
 * @export
 * @class ResearcherKnowledgeBaseApi
 * @extends {BaseAPI}
 */
export class ResearcherKnowledgeBaseApi extends BaseAPI {
    /**
     * 
     * @summary Send request for Knowledge Bases access
     * @param {string} id Knowledge Base identifier
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ResearcherKnowledgeBaseApi
     */
    public async acceptRules(id: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return ResearcherKnowledgeBaseApiFp(this.configuration).acceptRules(id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Get Paged Knowledge Bases
     * @param {number} page Page number
     * @param {number} limit Page size
     * @param {Array<string>} [sort] Sorting type
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ResearcherKnowledgeBaseApi
     */
    public async getAllKnowledgeBases(page: number, limit: number, sort?: Array<string>, options?: AxiosRequestConfig) : Promise<AxiosResponse<GetPagedKnowledgeBases>> {
        return ResearcherKnowledgeBaseApiFp(this.configuration).getAllKnowledgeBases(page, limit, sort, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Get Knowledge Bases
     * @param {string} id Knowledge Base identifier
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ResearcherKnowledgeBaseApi
     */
    public async getKnowledgeBase(id: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<KnowledgeBase>> {
        return ResearcherKnowledgeBaseApiFp(this.configuration).getKnowledgeBase(id, options).then((request) => request(this.axios, this.basePath));
    }
}
