/* tslint:disable */
/* eslint-disable */
/**
 * Swagger Data Provider
 * Документация API Провайдера Данных
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { KnowledgeBaseSession } from '../models';
/**
 * ResearcherKnowledgeSessionApi - axios parameter creator
 * @export
 */
export const ResearcherKnowledgeSessionApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Stop session
         * @param {string} id Knowledge Base identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        closeSession: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling closeSession.');
            }
            const localVarPath = `/api/v1/knoledge-bases/{id}/session/close`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2_Local required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken("OAuth2_Local", ["knowledge-base:read"])
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create session
         * @param {string} id Knowledge Base identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createNewSession: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling createNewSession.');
            }
            const localVarPath = `/api/v1/knoledge-bases/{id}/session`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2_Local required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken("OAuth2_Local", ["knowledge-base:read"])
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get active session
         * @param {string} id Knowledge Base identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getActiveSession: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/session/active`
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2_Local required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken("OAuth2_Local", ["knowledge-base:read"])
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Session prolongation
         * @param {string} id Knowledge Base identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        prolongationSession: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling prolongationSession.');
            }
            const localVarPath = `/api/v1/knoledge-bases/{id}/session/prolongation`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2_Local required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken("OAuth2_Local", ["knowledge-base:read"])
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ResearcherKnowledgeSessionApi - functional programming interface
 * @export
 */
export const ResearcherKnowledgeSessionApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Stop session
         * @param {string} id Knowledge Base identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async closeSession(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<KnowledgeBaseSession>>> {
            const localVarAxiosArgs = await ResearcherKnowledgeSessionApiAxiosParamCreator(configuration).closeSession(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Create session
         * @param {string} id Knowledge Base identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createNewSession(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<KnowledgeBaseSession>>> {
            const localVarAxiosArgs = await ResearcherKnowledgeSessionApiAxiosParamCreator(configuration).createNewSession(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Get active session
         * @param {string} id Knowledge Base identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getActiveSession(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<KnowledgeBaseSession>>> {
            const localVarAxiosArgs = await ResearcherKnowledgeSessionApiAxiosParamCreator(configuration).getActiveSession(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Session prolongation
         * @param {string} id Knowledge Base identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async prolongationSession(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<KnowledgeBaseSession>>> {
            const localVarAxiosArgs = await ResearcherKnowledgeSessionApiAxiosParamCreator(configuration).prolongationSession(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * ResearcherKnowledgeSessionApi - factory interface
 * @export
 */
export const ResearcherKnowledgeSessionApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Stop session
         * @param {string} id Knowledge Base identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async closeSession(id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<KnowledgeBaseSession>> {
            return ResearcherKnowledgeSessionApiFp(configuration).closeSession(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create session
         * @param {string} id Knowledge Base identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createNewSession(id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<KnowledgeBaseSession>> {
            return ResearcherKnowledgeSessionApiFp(configuration).createNewSession(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get active session
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getActiveSession(options?: AxiosRequestConfig): Promise<AxiosResponse<KnowledgeBaseSession>> {
            return ResearcherKnowledgeSessionApiFp(configuration).getActiveSession(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Session prolongation
         * @param {string} id Knowledge Base identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async prolongationSession(id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<KnowledgeBaseSession>> {
            return ResearcherKnowledgeSessionApiFp(configuration).prolongationSession(id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ResearcherKnowledgeSessionApi - object-oriented interface
 * @export
 * @class ResearcherKnowledgeSessionApi
 * @extends {BaseAPI}
 */
export class ResearcherKnowledgeSessionApi extends BaseAPI {
    /**
     * 
     * @summary Stop session
     * @param {string} id Knowledge Base identifier
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ResearcherKnowledgeSessionApi
     */
    public async closeSession(id: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<KnowledgeBaseSession>> {
        return ResearcherKnowledgeSessionApiFp(this.configuration).closeSession(id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Create session
     * @param {string} id Knowledge Base identifier
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ResearcherKnowledgeSessionApi
     */
    public async createNewSession(id: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<KnowledgeBaseSession>> {
        return ResearcherKnowledgeSessionApiFp(this.configuration).createNewSession(id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Get active session
     * @param {string} id Knowledge Base identifier
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ResearcherKnowledgeSessionApi
     */
    public async getActiveSession(id: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<KnowledgeBaseSession>> {
        return ResearcherKnowledgeSessionApiFp(this.configuration).getActiveSession(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Session prolongation
     * @param {string} id Knowledge Base identifier
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ResearcherKnowledgeSessionApi
     */
    public async prolongationSession(id: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<KnowledgeBaseSession>> {
        return ResearcherKnowledgeSessionApiFp(this.configuration).prolongationSession(id, options).then((request) => request(this.axios, this.basePath));
    }
}
