/* tslint:disable */
/* eslint-disable */
/**
 * Swagger Data Provider
 * Документация API Провайдера Данных
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { KnowledgeBaseSession } from './knowledge-base-session';
import { Pagination } from './pagination';
import { ShortKnowledgeBase } from './short-knowledge-base';
 /**
 * Paged Knowledge Base
 *
 * @export
 * @interface GetPagedKnowledgeBases
 */
export interface GetPagedKnowledgeBases {

    /**
     * Knowledge Base List
     *
     * @type {Array<ShortKnowledgeBase>}
     * @memberof GetPagedKnowledgeBases
     */
    content?: Array<ShortKnowledgeBase>;

    /**
     * @type {Pagination}
     * @memberof GetPagedKnowledgeBases
     */
    pagination: Pagination;

    /**
     * @type {KnowledgeBaseSession}
     * @memberof GetPagedKnowledgeBases
     */
    activeSession?: KnowledgeBaseSession;
}
