/* tslint:disable */
/* eslint-disable */
/**
 * Swagger Data Provider
 * Документация API Провайдера Данных
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * Knowledge Base credentials
 *
 * @export
 * @interface KnowledgeBaseDataCredentials
 */
export interface KnowledgeBaseDataCredentials {

    /**
     * Knowledge Base username
     *
     * @type {string}
     * @memberof KnowledgeBaseDataCredentials
     */
    username: string;

    /**
     * Knowledge Base password
     *
     * @type {string}
     * @memberof KnowledgeBaseDataCredentials
     */
    password: string;
}
