/* tslint:disable */
/* eslint-disable */
/**
 * Swagger Data Provider
 * Документация API Провайдера Данных
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { KnowledgeBaseDataCredentials } from './knowledge-base-data-credentials';
import { KnowledgeBaseDataFiles } from './knowledge-base-data-files';
 /**
 * Knowledge Base Data
 *
 * @export
 * @interface KnowledgeBaseData
 */
export interface KnowledgeBaseData {

    /**
     * @type {KnowledgeBaseDataCredentials}
     * @memberof KnowledgeBaseData
     */
    credentials?: KnowledgeBaseDataCredentials;

    /**
     * Files information
     *
     * @type {Array<KnowledgeBaseDataFiles>}
     * @memberof KnowledgeBaseData
     */
    files?: Array<KnowledgeBaseDataFiles>;
}
