/* tslint:disable */
/* eslint-disable */
/**
 * Swagger Data Provider
 * Документация API Провайдера Данных
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * Pagination Info
 *
 * @export
 * @interface Pagination
 */
export interface Pagination {

    /**
     * Total records
     *
     * @type {number}
     * @memberof Pagination
     * @example 20
     */
    totalRecords: number;

    /**
     * Current page
     *
     * @type {number}
     * @memberof Pagination
     * @example 0
     */
    currentPage: number;

    /**
     * Total pages
     *
     * @type {number}
     * @memberof Pagination
     * @example 2
     */
    totalPages: number;

    /**
     * Next page
     *
     * @type {number}
     * @memberof Pagination
     * @example 1
     */
    nextPage?: number;

    /**
     * Previous page
     *
     * @type {number}
     * @memberof Pagination
     */
    prevPage?: number;
}
